### ISSUE TITLE
Sensor ID's

### ISSUE THREAD

**Issue by Sjoekie** [patrickvorgers/HA-Import-Toon-Data#1]
Hello Patrick,

i am trying to get my toon2 data to home assistant, yet i am missing the electricity sensors in the "statistics meta" table.

There are only 2 gas sensors avaiable, no others.

the sensors for electicity are on home assistant, and 1 have an 6 month history there. so they must be available.

**Fixed : I had to remove a filter.** 

Did execute the script with failures. Got Syntaxis errors around a bunch of /* */ commented out lines, first at line 269. 
 
greets, Stefan

**Comment by Sjoekie** [comment]
Removed the comments at 269

now the following error appears:

> Execution finished with errors.
Result: near "FROM": syntax error
At line 271:
WITH CTE_DIFF_NT_ORIG_VALUE AS (
	SELECT ts, round(value - (lag(value, 1, 0) OVER (ORDER BY ts)), 3) AS diff
	FROM NT_ORIG_NEW
	ORDER BY ts
)
UPDATE NT_ORIG_NEW
SET diff = CTE_DIFF_NT_ORIG_VALUE.diff
FROM

**Comment by patrickvorgers** [comment]
Which version of the sqlitebrowser are you using?
Could you execute the "faulty" SQL statement separately outside of the script and see what kind of message it gives?

**Comment by Sjoekie** [comment]
I did download the windows portable app of DBBrowser SQLite, after switching to the 64-bit installer the syntaxis error dissapeared. 

The conversion did not worked out so far, there is no history in the Energy Dashboard. 
The only thing what was different was the Shema Version, this was 42.
I checked the collums in the statistics and short_term_statistics, i think they are okay.

**Comment by patrickvorgers** [comment]
Did you make sure that the core is still stopped while copying the database back?
- Stop the Home Assistant core (Developer tools/Services/Call service: Home Assistant Core Integration: Stop)

If Home Assistant core is running than the database gets corrupted if you replace it with another one!

**Comment by Sjoekie** [comment]
I did stop the recorder and home assistant core, did not check if it was still stopped when i put the database back.
Once the core is stopped, it should stay stopped. Wouldn't it?

**Comment by Sjoekie** [comment]
Did it al over again with the new "almost" empty database, this time it worked flawless. 
This was with schema version 42 only, the first try was with combined databases. 
Maybe this was the issue.

Problem solved so far! 
(the other historic data from the solaredge is gone, my bad. Did backup the old database but was corrupted too.)

**Comment by patrickvorgers** [comment]
The combined schema's was probably the issue, but atleast the issue is resolved!
Enjoy having your historic Toon data in Home Assistant
